os:
  - linux
language: c
env:
  - TARGET=c M32=
  - TARGET=c M32=-m32
install: sh -e install-deps.sh install_${TRAVIS_OS_NAME:-linux}
script: make check  M32=$M32 TARGET=$TARGET
notifications:
  email: lars@nocrew.org
